[pytest]
pythonpath = src
addopts = --import-mode=importlib
testpaths = src/cozmo_companion
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
